// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_r20padjXZEr1I68IDUgYjspXeCLYTR0',
    appId: '1:1082762279866:web:dd8b2d724c62436acafb83',
    messagingSenderId: '1082762279866',
    projectId: 'kakeibo-app-64231',
    authDomain: 'kakeibo-app-64231.firebaseapp.com',
    storageBucket: 'kakeibo-app-64231.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWPjtfQ_D12pEkf3ah2gphuNYV7FyyjdM',
    appId: '1:1082762279866:android:fdc1553eb8b01e4bcafb83',
    messagingSenderId: '1082762279866',
    projectId: 'kakeibo-app-64231',
    storageBucket: 'kakeibo-app-64231.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBleEXkdsoBWhMpOBmTY_6thOYQ5hR7bF8',
    appId: '1:1082762279866:ios:86ff9882d6ef407ecafb83',
    messagingSenderId: '1082762279866',
    projectId: 'kakeibo-app-64231',
    storageBucket: 'kakeibo-app-64231.firebasestorage.app',
    iosBundleId: 'com.example.kakeiboAppMvp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBleEXkdsoBWhMpOBmTY_6thOYQ5hR7bF8',
    appId: '1:1082762279866:ios:86ff9882d6ef407ecafb83',
    messagingSenderId: '1082762279866',
    projectId: 'kakeibo-app-64231',
    storageBucket: 'kakeibo-app-64231.firebasestorage.app',
    iosBundleId: 'com.example.kakeiboAppMvp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_r20padjXZEr1I68IDUgYjspXeCLYTR0',
    appId: '1:1082762279866:web:6a47b3a461a2d6d3cafb83',
    messagingSenderId: '1082762279866',
    projectId: 'kakeibo-app-64231',
    authDomain: 'kakeibo-app-64231.firebaseapp.com',
    storageBucket: 'kakeibo-app-64231.firebasestorage.app',
  );
}
